# Generated by Django 5.0.3 on 2024-03-25 17:40

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('communication_type', models.CharField(choices=[('سامانه پیامکی', 'سامانه پیامکی'), ('ربات تلگرام', 'ربات تلگرام')], default='سامانه پیامکی', max_length=255, verbose_name='نوع کانال ارتباطی')),
                ('code', models.CharField(max_length=255, verbose_name='کد')),
                ('phone_number', models.CharField(max_length=255, verbose_name='شماره')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت - ریال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_communication_channel', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_communication_channel', to=settings.AUTH_USER_MODEL, verbose_name='بروز شده توسط')),
            ],
            options={
                'verbose_name': 'کانال ارتباطی',
                'verbose_name_plural': 'کانال های ارتباطی',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForwardToPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('communication_type', models.CharField(choices=[('سامانه پیامکی', 'سامانه پیامکی'), ('ربات تلگرام', 'ربات تلگرام')], default='سامانه پیامکی', max_length=255, verbose_name='نوع کانال ارتباطی')),
                ('code', models.CharField(max_length=255, verbose_name='کد')),
                ('address', models.CharField(max_length=3000, verbose_name='آدرس')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت - ریال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_forward_to_portal', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_forward_to_portal', to=settings.AUTH_USER_MODEL, verbose_name='بروز شده توسط')),
            ],
            options={
                'verbose_name': 'انتقال دهنده',
                'verbose_name_plural': 'انتقال دهندگان',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('type', models.CharField(choices=[('کالا', 'کالا'), ('خدمات', 'خدمات')], default='کالا', max_length=255, verbose_name='نوع محصول')),
                ('code', models.CharField(max_length=255, verbose_name='کد')),
                ('weight', models.IntegerField(default=0, verbose_name='وزن - گرم')),
                ('size', models.IntegerField(default=0, verbose_name='سایز - اینچ')),
                ('color', models.CharField(max_length=255, verbose_name='رنگ')),
                ('product_price', models.IntegerField(default=0, verbose_name='هزینه خام محصول - ریال')),
                ('shipping_price', models.IntegerField(default=0, verbose_name='هزینه حمل - ریال')),
                ('send_link_price', models.IntegerField(default=0, verbose_name='هزینه ارسال لینک - ریال')),
                ('packing_price', models.IntegerField(default=0, verbose_name='هزینه بسته بندی - ریال')),
                ('seller_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='کمیسیون فروشنده - درصد')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_product', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('images', models.ManyToManyField(blank=True, related_name='images_product', to='gallery.filegallery', verbose_name='تصاویر')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_product', to=settings.AUTH_USER_MODEL, verbose_name='بروز شده توسط')),
                ('videos', models.ManyToManyField(blank=True, related_name='videos_product', to='gallery.filegallery', verbose_name='ویدیو ها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('receiving_type', models.CharField(choices=[('شماره موبایل', 'شماره موبایل'), ('شماره سامانه', 'شماره سامانه'), ('Qr Code', 'Qr Code'), ('لینک', 'لینک'), ('صفحه فرود شبکه اجتماعی', 'صفحه فرود شبکه اجتماعی'), ('صفحه فرود فروشگاه اینترنتی', 'صفحه فرود فروشگاه اینترنتی')], default='شماره موبایل', max_length=255, verbose_name='نوع دریافت')),
                ('code', models.CharField(max_length=255, verbose_name='کد')),
                ('receiver_phone_number', models.CharField(max_length=255, verbose_name='شماره')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت - ریال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_receiver', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_receiver', to=settings.AUTH_USER_MODEL, verbose_name='بروز شده توسط')),
            ],
            options={
                'verbose_name': 'دریافت کننده',
                'verbose_name_plural': 'دریافت کننده ها',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('register_type', models.CharField(choices=[('تخصیص دستی', 'تخصیص دستی'), ('تخصیص خودکار', 'تخصیص خودکار'), ('تخصیص خودکار بر اساس عملکرد', 'تخصیص خودکار بر اساس عملکرد')], default='تخصیص دستی', max_length=255, verbose_name='نوع تخصیص')),
                ('code', models.CharField(max_length=255, verbose_name='کد')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_registrar', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_registrar', to=settings.AUTH_USER_MODEL, verbose_name='بروز شده توسط')),
            ],
            options={
                'verbose_name': 'تخصیص دهنده',
                'verbose_name_plural': 'تخصیص دهنده ها',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResellerNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('network_type', models.CharField(choices=[('ماهواره', 'ماهواره'), ('تلویزیون', 'تلویزیون'), ('شبکه اجتماعی', 'شبکه اجتماعی')], default='ماهواره', max_length=255, verbose_name='نوع محتوا')),
                ('code', models.CharField(max_length=255, verbose_name='کد')),
                ('broadcast_direction', models.CharField(choices=[('یاه ست', 'یاه ست'), ('هات برد', 'هات برد'), ('ترکمن عالم', 'ترکمن عالم')], default='ماهواره', max_length=255, verbose_name='جهت پخش')),
                ('company_name', models.CharField(max_length=255, verbose_name='نام کمپانی')),
                ('owner_name', models.CharField(max_length=255, verbose_name='نام صاحب')),
                ('broker_name', models.CharField(max_length=255, verbose_name='نام واسط')),
                ('broadcast_price', models.IntegerField(default=0, verbose_name='هزینه پخش - ریال')),
                ('subtitle_price', models.IntegerField(default=0, verbose_name='هزینه زیرنویس - ریال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_reseller_network', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_reseller_network', to=settings.AUTH_USER_MODEL, verbose_name='بروز شده توسط')),
            ],
            options={
                'verbose_name': 'شبکه',
                'verbose_name_plural': 'شبکه ها',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeaserMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('content_type', models.CharField(choices=[('صوتی', 'صوتی'), ('تصویری', 'تصویری'), ('ویدئویی', 'ویدئویی'), ('متنی', 'متنی'), ('تلفیقی', 'تلفیقی'), ('اینستاگرامی', 'اینستاگرامی')], default='صوتی', max_length=255, verbose_name='نوع محتوا')),
                ('code', models.CharField(max_length=255, verbose_name='کد')),
                ('address', models.CharField(max_length=2000, verbose_name='ادرس')),
                ('phone_number', models.CharField(max_length=255, verbose_name='شماره تماس')),
                ('creation_price', models.IntegerField(default=0, verbose_name='هزینه ساخت - ریال')),
                ('editing_price', models.IntegerField(default=0, verbose_name='هزینه ویرایش - ریال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_creator', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_creator', to=settings.AUTH_USER_MODEL, verbose_name='بروز شده توسط')),
            ],
            options={
                'verbose_name': 'تیزر ساز',
                'verbose_name_plural': 'تیزر ساز ها',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertiseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('advertise_content_type', models.CharField(choices=[('محتوای ویدیویی تلویزیون', 'محتوای ویدیویی تلویزیون'), ('محتوای ویدیویی ماهواره', 'محتوای ویدیویی ماهواره'), ('محتوای ویدیویی شبکه اجتماعی', 'محتوای ویدیویی شبکه اجتماعی'), ('محتوای تصویری', 'محتوای تصویری'), ('محتوای متنی (زیرنویس)', 'محتوای متنی (زیرنویس)'), ('محتوای صوتی (نریشن)', 'محتوای صوتی (نریشن)')], default='محتوای ویدیویی تلویزیون', max_length=255, verbose_name='نوع محتوای تبلیغ')),
                ('code', models.CharField(max_length=255, verbose_name='کد')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی')),
                ('content', models.ManyToManyField(blank=True, related_name='content_advertise_content', to='gallery.filegallery', verbose_name='محتوا')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_advertise_content', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_advertise_content', to=settings.AUTH_USER_MODEL, verbose_name='بروز شده توسط')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_advertise_content', to='portal.product', verbose_name='محصول')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_advertise_content', to='portal.receiver', verbose_name='دریافت کننده')),
                ('reseller_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseller_network_advertise_content', to='portal.resellernetwork', verbose_name='شبکه تبلیغ کننده')),
                ('teaser_maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaser_maker_advertise_content', to='portal.teasermaker', verbose_name='تیزر ساز')),
            ],
            options={
                'verbose_name': 'محتوای تبلیغاتی',
                'verbose_name_plural': 'محتوا های تبلیغاتی',
                'ordering': ['created_at'],
            },
        ),
    ]
