# Generated by Django 5.0.3 on 2024-04-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='غیر فعال'),
        ),
    ]
