# Generated by Django 5.0.3 on 2024-04-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_product_disabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='disabled',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
    ]
