# Generated by Django 5.0.3 on 2024-05-20 13:49

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWarehouseThreadIsActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='بروز شده در')),
            ],
            options={
                'verbose_name': 'بررسی انبار سیستم',
                'verbose_name_plural': 'بررسی انبار سیستم',
            },
        ),
        migrations.CreateModel(
            name='RequestedProductThreadIsActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='بروز شده در')),
            ],
            options={
                'verbose_name': 'بررسی محصول سیستم',
                'verbose_name_plural': 'بررسی محصول سیستم',
            },
        ),
    ]
