# Generated by Django 5.0.3 on 2024-06-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_rename_register_type_registrar_registrar_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrar',
            options={'ordering': ['-created_at'], 'verbose_name': 'تخصیص دهنده', 'verbose_name_plural': 'تخصیص دهنده ها'},
        ),
        migrations.AlterField(
            model_name='forwardtoportal',
            name='communication_type',
            field=models.CharField(choices=[('اپلیکیشن خارجی', 'اپلیکیشن خارجی'), ('اپلیکیشن بومی', 'اپلیکیشن بومی')], default='اپلیکیشن خارجی', max_length=255, verbose_name='نوع انتقال دهنده'),
        ),
        migrations.DeleteModel(
            name='ProductWarehouse',
        ),
    ]
