# Generated by Django 5.0.3 on 2024-05-11 13:41

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('has_access_to_section', models.CharField(choices=[('user', 'کاربر'), ('permission', 'مجوز'), ('role', 'نقش'), ('resource', 'منابع'), ('product', 'محصولات'), ('teaser_maker', 'تیزر ساز'), ('reseller_network', 'شبکه'), ('receiver', 'دریافت کننده'), ('advertise_content', 'محتوای تبلیغاتی'), ('forward_to_portal', 'انتقال دهنده'), ('communication_channel', 'کانال ارتباطی'), ('registrar', 'تخصیص دهنده'), ('automation', 'اتوماسیون'), ('automation_project', 'اتوماسیون - ساخت پروژه'), ('automation_task', 'اتوماسیون - ایجاد وظیفه'), ('automation_communicate', 'اتوماسیون - مکاتبات'), ('ticket_admin', 'تیکت ادمین'), ('ticket', 'تیکت'), ('message', 'پیام'), ('notification', 'اطلاعیه')], max_length=255, verbose_name='دسترسی به بخش')),
                ('read', models.BooleanField(default=True, verbose_name='خواندن')),
                ('create', models.BooleanField(default=True, verbose_name='ایجاد')),
                ('modify', models.BooleanField(default=True, verbose_name='ویرایش')),
                ('delete', models.BooleanField(default=True, verbose_name='حذف')),
            ],
            options={
                'verbose_name': 'دسترسی',
                'verbose_name_plural': 'دسترسی ها',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('permissions', models.ManyToManyField(blank=True, to='accounts.permission', verbose_name='اجازه ها')),
            ],
            options={
                'verbose_name': 'نقش',
                'verbose_name_plural': 'نقش ها',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد ملی')),
                ('mobile_phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره همراه')),
                ('landline', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره ثابت')),
                ('birthday', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('card_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره کارت')),
                ('isbn', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره شبا')),
                ('address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='آدرس')),
                ('daily_allowed_product_processing_number', models.IntegerField(default=0, verbose_name='تعداد مجاز فروش محصولات روزانه')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_roles', to='accounts.role', verbose_name='نقش')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها',
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_seen_by_user', models.BooleanField(default=False, verbose_name='دیده شده توسط کاربر')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('notification', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='notification_user_notification', to='tickets.notification', verbose_name='اطلاعیه')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_user_notification', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اطلاعیه کاربر',
                'verbose_name_plural': 'اطلاعیه های کاربران',
            },
        ),
    ]
