# Generated by Django 5.0.3 on 2024-05-20 13:49

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=True, verbose_name='خواندن')),
                ('create', models.BooleanField(default=True, verbose_name='ایجاد')),
                ('modify', models.BooleanField(default=True, verbose_name='ویرایش')),
                ('delete', models.BooleanField(default=True, verbose_name='حذف')),
            ],
            options={
                'verbose_name': 'اجازه',
                'verbose_name_plural': 'اجازه ها',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=255, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'بخش',
                'verbose_name_plural': 'بخش ها',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('role', models.CharField(choices=[('manager', 'مدیر'), ('user', 'کاربر'), ('seller', 'فروشنده'), ('warehouse_keeper', 'انباردار'), ('delivery_person', 'ارسال کننده')], default='user', max_length=255, verbose_name='نقش')),
                ('permissions', models.ManyToManyField(blank=True, to='accounts.permission', verbose_name='اجازه ها')),
            ],
            options={
                'verbose_name': 'نقش',
                'verbose_name_plural': 'نقش ها',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد ملی')),
                ('mobile_phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره همراه')),
                ('landline', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره ثابت')),
                ('birthday', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('card_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره کارت')),
                ('isbn', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره شبا')),
                ('address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='آدرس')),
                ('daily_allowed_product_processing_number', models.IntegerField(default=0, verbose_name='تعداد مجاز فروش محصولات روزانه')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('roles', models.ManyToManyField(blank=True, related_name='roles_profile', to='accounts.role', verbose_name='نقش ها')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها',
            },
        ),
        migrations.AddField(
            model_name='permission',
            name='has_access_to_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_access_to_section_permission', to='accounts.section', verbose_name='دسترسی به بخش'),
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_allowed_product_processing_number', models.PositiveIntegerField(default=0, verbose_name='تعداد مجاز فروش محصولات روزانه')),
                ('profile', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='profile_seller_profile', to='accounts.profile', verbose_name='پروفایل کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل فروشنده',
                'verbose_name_plural': 'پروفایل های فروشندگان',
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_seen_by_user', models.BooleanField(default=False, verbose_name='دیده شده توسط کاربر')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('notification', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='notification_user_notification', to='tickets.notification', verbose_name='اطلاعیه')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_user_notification', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اطلاعیه کاربر',
                'verbose_name_plural': 'اطلاعیه های کاربران',
            },
        ),
    ]
