# Generated by Django 5.0.3 on 2024-04-08 11:04

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسترسی',
                'verbose_name_plural': 'دسترسی ها',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد ملی')),
                ('mobile_phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره همراه')),
                ('landline', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره ثابت')),
                ('birthday', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('card_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره کارت')),
                ('isbn', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره شبا')),
                ('address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='آدرس')),
                ('permissions', models.ManyToManyField(blank=True, related_name='profile_permissions', to='accounts.permission', verbose_name='دسترسی ها')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها',
            },
        ),
    ]
