# Generated by Django 5.0.3 on 2024-05-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['id'], 'verbose_name': 'اجازه', 'verbose_name_plural': 'اجازه ها'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['id'], 'verbose_name': 'نقش', 'verbose_name_plural': 'نقش ها'},
        ),
    ]
