# Generated by Django 5.0.3 on 2024-04-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='create',
            field=models.BooleanField(default=True, verbose_name='ایجاد کردن'),
        ),
        migrations.AddField(
            model_name='permission',
            name='has_access_to_section',
            field=models.CharField(choices=[('مدیر', 'مدیر'), ('معاون', 'معاون'), ('کارمند', 'کارمند')], default=1, max_length=255, verbose_name='دسترسی به بخش'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='modify',
            field=models.BooleanField(default=True, verbose_name='ویرایش کردن'),
        ),
        migrations.AddField(
            model_name='permission',
            name='read',
            field=models.BooleanField(default=True, verbose_name='خواندن'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='title',
            field=models.CharField(choices=[('مدیر', 'مدیر'), ('معاون', 'معاون'), ('کارمند', 'کارمند')], max_length=255, verbose_name='عنوان'),
        ),
    ]
