# Generated by Django 5.0.3 on 2024-04-08 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_permission_create_permission_has_access_to_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='permissions',
        ),
        migrations.AlterField(
            model_name='permission',
            name='has_access_to_section',
            field=models.CharField(choices=[('کاربر', 'کاربر')], max_length=255, verbose_name='دسترسی به بخش'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('permissions', models.ManyToManyField(blank=True, to='accounts.permission', verbose_name='اجازه ها')),
            ],
            options={
                'verbose_name': 'نقش',
                'verbose_name_plural': 'نقش ها',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_roles', to='accounts.role', verbose_name='نقش'),
        ),
    ]
