# Generated by Django 5.0.3 on 2024-05-20 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_section_name_fa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='daily_allowed_product_processing_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='roles',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_profile', to='accounts.role', verbose_name='نقش'),
        ),
    ]
