# Generated by Django 5.0.3 on 2024-05-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_permission_options_alter_role_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryprofile',
            name='delivery_allowance',
            field=models.BooleanField(default=False, verbose_name='آیا اجازه ارسال کالا دارد؟'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='sale_allowance',
            field=models.BooleanField(default=False, verbose_name='آیا اجازه فروش دارد؟'),
        ),
        migrations.AddField(
            model_name='warehouseprofile',
            name='warehouse_allowance',
            field=models.BooleanField(default=False, verbose_name='آیا اجازه انبار داری دارد؟'),
        ),
    ]
