# Generated by Django 5.0.3 on 2024-05-20 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_daily_allowed_product_processing_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerprofile',
            options={'verbose_name': 'فروشنده', 'verbose_name_plural': 'فروشندگان'},
        ),
        migrations.CreateModel(
            name='DeliveryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='profile_delivery_profile', to='accounts.profile', verbose_name='پروفایل کاربر')),
            ],
            options={
                'verbose_name': 'ارسال کننده',
                'verbose_name_plural': 'ارسال کننده گان',
            },
        ),
        migrations.CreateModel(
            name='WarehouseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='profile_warehouse_profile', to='accounts.profile', verbose_name='پروفایل کاربر')),
            ],
            options={
                'verbose_name': 'انباردار',
                'verbose_name_plural': 'انبار داران',
            },
        ),
    ]
