# Generated by Django 5.0.3 on 2024-04-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='delete',
            field=models.BooleanField(default=True, verbose_name='حذف'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='create',
            field=models.BooleanField(default=True, verbose_name='ایجاد'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='has_access_to_section',
            field=models.CharField(choices=[('user', 'کاربر'), ('permission', 'دسترسی'), ('role', 'نقش')], max_length=255, verbose_name='دسترسی به بخش'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='modify',
            field=models.BooleanField(default=True, verbose_name='ویرایش'),
        ),
    ]
