# Generated by Django 5.0.3 on 2024-04-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_permission_delete_alter_permission_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='has_access_to_section',
            field=models.CharField(choices=[('user', 'کاربر'), ('permission', 'مجوز'), ('role', 'نقش'), ('resource', 'منابع'), ('product', 'محصولات'), ('teaser_maker', 'تیزر ساز'), ('reseller_network', 'شبکه'), ('receiver', 'دریافت کننده'), ('advertise_content', 'محتوای تبلیغاتی'), ('forward_to_portal', 'انتقال دهنده'), ('communication_channel', 'کانال ارتباطی'), ('registrar', 'تخصیص دهنده')], max_length=255, verbose_name='دسترسی به بخش'),
        ),
    ]
