# Generated by Django 5.0.3 on 2024-05-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_permission_has_access_to_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='has_access_to_section',
            field=models.CharField(choices=[('user', 'کاربر'), ('permission', 'مجوز'), ('role', 'نقش'), ('resource', 'منابع'), ('product', 'محصولات'), ('teaser_maker', 'تیزر ساز'), ('reseller_network', 'شبکه'), ('receiver', 'دریافت کننده'), ('advertise_content', 'محتوای تبلیغاتی'), ('forward_to_portal', 'انتقال دهنده'), ('communication_channel', 'کانال ارتباطی'), ('registrar', 'تخصیص دهنده'), ('automation', 'اتوماسیون'), ('automation_project', 'اتوماسیون - ساخت پروژه'), ('automation_task', 'اتوماسیون - ایجاد وظیفه'), ('automation_communicate', 'اتوماسیون - مکاتبات'), ('ticket_admin', 'تیکت ادمین'), ('ticket', 'تیکت'), ('message', 'پیام'), ('notification', 'اطلاعیه')], max_length=255, verbose_name='دسترسی به بخش'),
        ),
    ]
