# Generated by Django 5.0.3 on 2024-05-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_usernotification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='daily_allowed_product_processing_number',
            field=models.IntegerField(default=0, verbose_name='تعداد مجاز فروش محصولات روزانه'),
        ),
    ]
