# Generated by Django 5.0.3 on 2024-05-20 13:49

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, verbose_name='نام بانک')),
                ('account_number', models.CharField(max_length=255, verbose_name='شماره حساب')),
                ('card_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره کارت')),
                ('isbn', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره شبا')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی')),
                ('broker', models.ManyToManyField(blank=True, related_name='broker_credit_card', to=settings.AUTH_USER_MODEL, verbose_name='کارگزار')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_credit_card', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_credit_card', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_credit_card', to=settings.AUTH_USER_MODEL, verbose_name='بروز شده توسط')),
            ],
            options={
                'verbose_name': 'کارت بانکی',
                'verbose_name_plural': 'کارت های بانکی',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255, verbose_name='شماره تماس')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام کامل')),
                ('age', models.CharField(blank=True, max_length=255, null=True, verbose_name='تاریخ تولد')),
                ('address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='آدرس')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('desired_product', models.ManyToManyField(blank=True, related_name='desired_product_customer', to='portal.product', verbose_name='محصولات مورد علاقه')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتری ها',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_product_available_at_warehouse', models.BooleanField(default=False, verbose_name='محصول در انبار موجود است؟')),
                ('is_processed', models.BooleanField(default=False, verbose_name='پردازش شده')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_requested_product', to='automation.customer', verbose_name='خریدار')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_requested_product', to='portal.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'محصول درخواستی',
                'verbose_name_plural': 'محصولات درخواستی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestedProductProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_department_status', models.CharField(choices=[('sales', 'فروش'), ('warehouse', 'انبار'), ('delivery', 'ارسال')], default='sales', max_length=255, verbose_name='واحد فعلی پردازش کننده محصول')),
                ('is_confirmed_by_sales_department', models.BooleanField(default=False, verbose_name='تایید واحد فروش')),
                ('sales_status', models.CharField(choices=[('processing', 'در حال پردازش'), ('soled', 'فروخته شده'), ('canceled', 'کنسل شده')], default='processing', max_length=255, verbose_name='وضعیت فروش محصول درخواستی')),
                ('product_price', models.IntegerField(blank=True, null=True, verbose_name='قیمت نهایی واحد محصول فروخته شده - ریال')),
                ('product_number', models.IntegerField(blank=True, null=True, verbose_name='تعداد محصول فروخته شده')),
                ('request_total_income', models.IntegerField(blank=True, null=True, verbose_name='درآمد نهایی این درخواست - ریال')),
                ('warehouse_status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('sent_to_delivery', 'تحویل به واحد ارسال'), ('return_to_sales', 'بازگشت به واحد فروش')], default='pending', max_length=255, verbose_name='وضعیت انبار محصول درخواستی')),
                ('is_confirmed_by_warehouse_keeper', models.BooleanField(default=False, verbose_name='تایید واحد انبار')),
                ('delivery_status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('delivered', 'تحویل شده به مشتری'), ('return_to_warehouse', 'بازگشت به واحد انبار')], default='pending', max_length=255, verbose_name='وضعیت ارسال محصول درخواستی')),
                ('is_confirmed_by_delivery_man', models.BooleanField(default=False, verbose_name='تایید واحد ارسال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('delivery_man', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_man_requested_product_processing', to=settings.AUTH_USER_MODEL, verbose_name='اختصاص یافته به')),
                ('requested_product', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='requested_product_requested_product_processing', to='automation.requestedproduct', verbose_name='محصول درخواستی')),
                ('seller', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='seller_requested_product_processing', to=settings.AUTH_USER_MODEL, verbose_name='اختصاص یافته به')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_requested_product_processing', to=settings.AUTH_USER_MODEL, verbose_name='بروز شده توسط')),
                ('warehouse_keeper', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_keeper_requested_product_processing', to=settings.AUTH_USER_MODEL, verbose_name='انباردار')),
            ],
            options={
                'verbose_name': 'پردازش محصول درخواستی',
                'verbose_name_plural': 'پردازش محصولات درخواستی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestedProductProcessingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('sales', 'فروش'), ('warehouse', 'انبار'), ('delivery', 'ارسال')], editable=False, max_length=255, verbose_name='واحد پردازش کننده محصول')),
                ('report', models.TextField(blank=True, null=True, verbose_name='گزارش')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_requested_product_processing_report', to=settings.AUTH_USER_MODEL, verbose_name='بروز شده توسط')),
                ('requested_product_processing', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='requested_product_processing_requested_product_processing_report', to='automation.requestedproductprocessing', verbose_name='محصول درخواستی پردازشی')),
            ],
            options={
                'verbose_name': 'گزارش پردازش محصول درخواستی',
                'verbose_name_plural': 'گزارشات پردازش محصولات درخواستی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=0, verbose_name='شماره مرتبط')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_product_relation', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_product_relation', to='portal.product', verbose_name='محصول')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_product_relation', to='portal.receiver', verbose_name='دریافت کننده')),
            ],
            options={
                'verbose_name': 'ارتباط محصول و دریافت کننده',
                'verbose_name_plural': 'ارتباط محصولات و دریافت کنندگان',
                'ordering': ['created_at'],
                'unique_together': {('product', 'receiver', 'number')},
            },
        ),
    ]
