# Generated by Django 5.0.3 on 2024-04-26 15:36

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_project', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'تیم',
                'verbose_name_plural': 'تیم ها',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='جزئیات')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_task', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('current_worker', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='task_current_worker', to=settings.AUTH_USER_MODEL, verbose_name='در حال اجرا توسط')),
                ('previous_worker', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='task_previous_worker', to=settings.AUTH_USER_MODEL, verbose_name='در حال اجرا توسط')),
            ],
            options={
                'verbose_name': 'وظیفه',
                'verbose_name_plural': 'وظایف',
                'ordering': ['created_at'],
            },
        ),
    ]
