# Generated by Django 5.0.3 on 2024-05-11 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedproductprocessing',
            name='delivery_man',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_man_requested_product_processing', to=settings.AUTH_USER_MODEL, verbose_name='اختصاص یافته به'),
        ),
        migrations.AlterField(
            model_name='requestedproductprocessing',
            name='warehouse_keeper',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_keeper_requested_product_processing', to=settings.AUTH_USER_MODEL, verbose_name='انباردار'),
        ),
    ]
