# Generated by Django 5.0.3 on 2024-05-21 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('automation', '0001_initial'),
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='desired_product',
            field=models.ManyToManyField(blank=True, related_name='desired_product_customer', to='portal.product', verbose_name='محصولات مورد علاقه'),
        ),
        migrations.AddField(
            model_name='productrelation',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_product_relation', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط'),
        ),
        migrations.AddField(
            model_name='productrelation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_product_relation', to='portal.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='productrelation',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_product_relation', to='portal.receiver', verbose_name='دریافت کننده'),
        ),
        migrations.AddField(
            model_name='requestedproduct',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_requested_product', to='automation.customer', verbose_name='خریدار'),
        ),
        migrations.AddField(
            model_name='requestedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_requested_product', to='portal.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='requestedproductprocessing',
            name='delivery_man',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_man_requested_product_processing', to='accounts.deliveryprofile', verbose_name='اختصاص یافته به'),
        ),
        migrations.AddField(
            model_name='requestedproductprocessing',
            name='requested_product',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='requested_product_requested_product_processing', to='automation.requestedproduct', verbose_name='محصول درخواستی'),
        ),
        migrations.AddField(
            model_name='requestedproductprocessing',
            name='seller',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='seller_requested_product_processing', to='accounts.sellerprofile', verbose_name='اختصاص یافته به'),
        ),
        migrations.AddField(
            model_name='requestedproductprocessing',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_requested_product_processing', to=settings.AUTH_USER_MODEL, verbose_name='بروز شده توسط'),
        ),
        migrations.AddField(
            model_name='requestedproductprocessing',
            name='warehouse_keeper',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_keeper_requested_product_processing', to='accounts.warehouseprofile', verbose_name='انباردار'),
        ),
        migrations.AddField(
            model_name='requestedproductprocessingreport',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_requested_product_processing_report', to=settings.AUTH_USER_MODEL, verbose_name='بروز شده توسط'),
        ),
        migrations.AddField(
            model_name='requestedproductprocessingreport',
            name='requested_product_processing',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='requested_product_processing_requested_product_processing_report', to='automation.requestedproductprocessing', verbose_name='محصول درخواستی پردازشی'),
        ),
        migrations.AlterUniqueTogether(
            name='productrelation',
            unique_together={('product', 'receiver', 'number')},
        ),
    ]
