# Generated by Django 5.0.3 on 2024-06-03 20:27

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        ('resource', '0003_alter_registrar_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_number', models.IntegerField(default=0, verbose_name='تعداد موجودی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_product_warehouse', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('product', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='product_product_warehouse', to='resource.product', verbose_name='محصول')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_product_warehouse', to=settings.AUTH_USER_MODEL, verbose_name='بروز شده توسط')),
            ],
            options={
                'verbose_name': 'اطلاعات جانبی محصول',
                'verbose_name_plural': 'اطلاعات جانبی محصولات',
                'ordering': ['created_at'],
            },
        ),
    ]
