# Generated by Django 5.0.3 on 2024-05-04 11:02

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, verbose_name='نام بانک')),
                ('account_number', models.CharField(max_length=255, verbose_name='شماره حساب')),
                ('card_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره کارت')),
                ('isbn', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره شبا')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_credit_card', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_credit_card', to=settings.AUTH_USER_MODEL, verbose_name='اوپراتور')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_credit_card', to=settings.AUTH_USER_MODEL, verbose_name='بروز شده توسط')),
            ],
            options={
                'verbose_name': 'کارت بانکی',
                'verbose_name_plural': 'کارت های بانکی',
                'ordering': ['created_at'],
            },
        ),
    ]
