# Generated by Django 5.0.3 on 2024-05-04 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_creditcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='operator',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_credit_card', to=settings.AUTH_USER_MODEL, verbose_name='کارگزار'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner_credit_card', to=settings.AUTH_USER_MODEL, verbose_name='دارنده حساب'),
            preserve_default=False,
        ),
    ]
