# Generated by Django 5.0.3 on 2024-05-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedproductprocessingreport',
            name='status',
            field=models.CharField(default=1, editable=False, max_length=255, verbose_name='وضعیت محصول'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestedproductprocessing',
            name='in_department_status',
            field=models.CharField(choices=[('sale', 'فروش'), ('warehouse', 'انبار'), ('delivery', 'ارسال')], default='sales', max_length=255, verbose_name='واحد فعلی پردازش کننده محصول'),
        ),
        migrations.AlterField(
            model_name='requestedproductprocessing',
            name='sales_status',
            field=models.CharField(choices=[('processing', 'در حال پردازش'), ('sold', 'فروخته شده'), ('canceled', 'کنسل شده'), ('pending_sales_approval', 'در انتظار تایید مدیریت فروش')], default='processing', max_length=255, verbose_name='وضعیت فروش محصول درخواستی'),
        ),
        migrations.AlterField(
            model_name='requestedproductprocessingreport',
            name='department',
            field=models.CharField(choices=[('sale', 'فروش'), ('warehouse', 'انبار'), ('delivery', 'ارسال')], editable=False, max_length=255, verbose_name='واحد پردازش کننده محصول'),
        ),
    ]
