# Generated by Django 5.0.3 on 2024-05-11 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_alter_requestedproductprocessing_delivery_man_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='broker',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='broker',
            field=models.ManyToManyField(blank=True, related_name='broker_credit_card', to=settings.AUTH_USER_MODEL, verbose_name='کارگزار'),
        ),
    ]
