# Generated by Django 5.0.3 on 2024-05-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_requestedproductprocessingreport_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedproductprocessing',
            name='cancel_number',
            field=models.IntegerField(default=0, verbose_name='تعداد کنسلی ها'),
        ),
    ]
