# Generated by Django 5.0.3 on 2024-05-04 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_remove_creditcard_operator_creditcard_broker_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_credit_card', to=settings.AUTH_USER_MODEL, verbose_name='مالک'),
        ),
    ]
