# Generated by Django 5.0.3 on 2024-05-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_requestedproductprocessing_cancel_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedproductprocessing',
            name='cancel_multiply',
            field=models.IntegerField(default=0, verbose_name='تعداد دفعات کنسلی با تغییر فروشنده'),
        ),
        migrations.AlterField(
            model_name='requestedproductprocessing',
            name='in_department_status',
            field=models.CharField(choices=[('sale', 'فروش'), ('warehouse', 'انبار'), ('delivery', 'ارسال')], default='sale', max_length=255, verbose_name='واحد فعلی پردازش کننده محصول'),
        ),
        migrations.AlterField(
            model_name='requestedproductprocessing',
            name='sales_status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('sold', 'فروخته شده'), ('canceled', 'کنسل شده'), ('pending_sales_approval', 'در انتظار تایید مدیریت فروش')], default='processing', max_length=255, verbose_name='وضعیت فروش محصول درخواستی'),
        ),
    ]
