# Generated by Django 5.0.3 on 2024-05-04 12:15

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_alter_creditcard_owner'),
        ('portal', '0005_alter_teasermaker_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255, verbose_name='شماره تماس')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام کامل')),
                ('age', models.CharField(max_length=255, verbose_name='تاریخ تولد')),
                ('address', models.CharField(max_length=1000, verbose_name='آدرس')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('desired_product', models.ManyToManyField(blank=True, related_name='desired_product_customer', to='portal.product', verbose_name='محصولات مورد علاقه')),
            ],
            options={
                'verbose_name': 'کارت بانکی',
                'verbose_name_plural': 'کارت های بانکی',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(default=False, verbose_name='خاتمه یافته')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_requested_product', to='automation.customer', verbose_name='خریدار')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_requested_product', to='portal.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'محصول درخواستی',
                'verbose_name_plural': 'محصولات درخواستی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestedProductProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('status', models.CharField(choices=[('processing', 'در حال پردازش'), ('soled', 'فروخته شده'), ('canceled', 'کنسل شده')], default='processing', max_length=255, verbose_name='وضعیت پردازش محصول درخواستی')),
                ('product_price', models.IntegerField(blank=True, null=True, verbose_name='قیمت نهایی واحد محصول فروخته شده - ریال')),
                ('product_number', models.IntegerField(blank=True, null=True, verbose_name='تعداد محصول فروخته شده')),
                ('request_total_income', models.IntegerField(blank=True, null=True, verbose_name='درآمد نهایی این درخواست - ریال')),
                ('assigned_to', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_requested_product_processing', to=settings.AUTH_USER_MODEL, verbose_name='اختصاص یافته به')),
                ('requested_product', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='requested_product_requested_product_processing', to='automation.requestedproduct', verbose_name='محصول درخواستی')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_requested_product_processing', to=settings.AUTH_USER_MODEL, verbose_name='بروز شده توسط')),
            ],
            options={
                'verbose_name': 'محصول درخواستی',
                'verbose_name_plural': 'محصولات درخواستی',
                'ordering': ['-created_at'],
            },
        ),
    ]
