# Generated by Django 5.0.3 on 2024-05-04 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_customer_requestedproduct_requestedproductprocessing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['created_at'], 'verbose_name': 'مشتری', 'verbose_name_plural': 'مشتری ها'},
        ),
        migrations.AlterModelOptions(
            name='requestedproductprocessing',
            options={'ordering': ['-created_at'], 'verbose_name': 'پردازش محصول درخواستی', 'verbose_name_plural': 'پردازش محصولات درخواستی'},
        ),
        migrations.RemoveField(
            model_name='requestedproductprocessing',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='requestedproductprocessing',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='requestedproductprocessing',
            name='status',
        ),
        migrations.AddField(
            model_name='requestedproduct',
            name='is_product_available_at_warehouse',
            field=models.BooleanField(default=False, verbose_name='محصول در انبار موجود است؟'),
        ),
        migrations.AddField(
            model_name='requestedproductprocessing',
            name='delivery_man',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_man_requested_product_processing', to=settings.AUTH_USER_MODEL, verbose_name='اختصاص یافته به'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestedproductprocessing',
            name='delivery_status',
            field=models.CharField(choices=[('processing', 'در حال پردازش'), ('delivered', 'تحویل شده'), ('canceled', 'کنسل شده')], default='processing', max_length=255, verbose_name='وضعیت انبار محصول درخواستی'),
        ),
        migrations.AddField(
            model_name='requestedproductprocessing',
            name='in_department_status',
            field=models.CharField(choices=[('sales', 'فروش'), ('warehouse', 'انبار'), ('delivery', 'ارسال')], default='processing', max_length=255, verbose_name='واحد فعلی پردازش کننده محصول'),
        ),
        migrations.AddField(
            model_name='requestedproductprocessing',
            name='is_confirmed_by_delivery_department',
            field=models.BooleanField(default=False, verbose_name='تایید مدیریت واحد ارسال'),
        ),
        migrations.AddField(
            model_name='requestedproductprocessing',
            name='is_confirmed_by_delivery_man',
            field=models.BooleanField(default=False, verbose_name='تایید واحد ارسال'),
        ),
        migrations.AddField(
            model_name='requestedproductprocessing',
            name='is_confirmed_by_sales_department',
            field=models.BooleanField(default=False, verbose_name='تایید واحد فروش'),
        ),
        migrations.AddField(
            model_name='requestedproductprocessing',
            name='is_confirmed_by_warehouse_department',
            field=models.BooleanField(default=False, verbose_name='تایید مدیریت واحد انبار'),
        ),
        migrations.AddField(
            model_name='requestedproductprocessing',
            name='is_confirmed_by_warehouse_keeper',
            field=models.BooleanField(default=False, verbose_name='تایید واحد انبار'),
        ),
        migrations.AddField(
            model_name='requestedproductprocessing',
            name='reports',
            field=models.TextField(blank=True, null=True, verbose_name='گزارش ها'),
        ),
        migrations.AddField(
            model_name='requestedproductprocessing',
            name='sales_status',
            field=models.CharField(choices=[('processing', 'در حال پردازش'), ('soled', 'فروخته شده'), ('canceled', 'کنسل شده')], default='processing', max_length=255, verbose_name='وضعیت فروش محصول درخواستی'),
        ),
        migrations.AddField(
            model_name='requestedproductprocessing',
            name='seller',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='seller_requested_product_processing', to=settings.AUTH_USER_MODEL, verbose_name='اختصاص یافته به'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestedproductprocessing',
            name='warehouse_keeper',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_keeper_requested_product_processing', to=settings.AUTH_USER_MODEL, verbose_name='انباردار'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestedproductprocessing',
            name='warehouse_status',
            field=models.CharField(choices=[('processing', 'در حال پردازش'), ('sent_out', 'ارسال شده'), ('canceled', 'کنسل شده')], default='processing', max_length=255, verbose_name='وضعیت انبار محصول درخواستی'),
        ),
    ]
