# Generated by Django 5.0.3 on 2024-05-27 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_permission_options_alter_role_options'),
        ('automation', '0005_requestedproductprocessing_cancel_multiply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedproductprocessing',
            name='seller',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_requested_product_processing', to='accounts.sellerprofile', verbose_name='اختصاص یافته به'),
        ),
    ]
