# Generated by Django 5.0.3 on 2024-05-27 11:16

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_permission_options_alter_role_options'),
        ('automation', '0006_alter_requestedproductprocessing_seller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedProductProcessingCancelReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_requested_product_processing_cancel_report', to=settings.AUTH_USER_MODEL, verbose_name='بروز شده توسط')),
                ('requested_product', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='requested_product_requested_product_processing_cancel_report', to='automation.requestedproduct', verbose_name='محصول درخواستی')),
                ('seller', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_requested_product_processing_cancel_report', to='accounts.sellerprofile', verbose_name='اختصاص یافته به')),
            ],
            options={
                'verbose_name': 'کنسلی پردازش محصول درخواستی',
                'verbose_name_plural': 'کنسلی های پردازش محصولات درخواستی',
                'ordering': ['-created_at'],
            },
        ),
    ]
