# Generated by Django 5.0.3 on 2024-05-04 14:12

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_alter_customer_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestedproductprocessing',
            name='reports',
        ),
        migrations.AlterField(
            model_name='requestedproductprocessing',
            name='delivery_status',
            field=models.CharField(choices=[('processing', 'در حال پردازش'), ('delivered', 'تحویل شده به مشتری'), ('canceled', 'کنسل شده')], default='processing', max_length=255, verbose_name='وضعیت انبار محصول درخواستی'),
        ),
        migrations.AlterField(
            model_name='requestedproductprocessing',
            name='in_department_status',
            field=models.CharField(choices=[('sales', 'فروش'), ('warehouse', 'انبار'), ('delivery', 'ارسال')], default='sales', max_length=255, verbose_name='واحد فعلی پردازش کننده محصول'),
        ),
        migrations.AlterField(
            model_name='requestedproductprocessing',
            name='warehouse_status',
            field=models.CharField(choices=[('processing', 'در حال پردازش'), ('sent_out', 'تحویل به واحد ارسال'), ('canceled', 'کنسل شده')], default='processing', max_length=255, verbose_name='وضعیت انبار محصول درخواستی'),
        ),
        migrations.CreateModel(
            name='RequestedProductProcessingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('sales', 'فروش'), ('warehouse', 'انبار'), ('delivery', 'ارسال')], max_length=255, verbose_name='واحد پردازش کننده محصول')),
                ('report', models.TextField(blank=True, null=True, verbose_name='گزارش')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_requested_product_processing_report', to=settings.AUTH_USER_MODEL, verbose_name='بروز شده توسط')),
                ('requested_product_processing', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='requested_product_processing_requested_product_processing_report', to='automation.requestedproductprocessing', verbose_name='محصول درخواستی پردازشی')),
            ],
            options={
                'verbose_name': 'گزارش پردازش محصول درخواستی',
                'verbose_name_plural': 'گزارشات پردازش محصولات درخواستی',
                'ordering': ['-created_at'],
            },
        ),
    ]
