# Generated by Django 5.0.3 on 2024-05-27 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_permission_options_alter_role_options'),
        ('automation', '0007_requestedproductprocessingcancelreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestedproductprocessingcancelreport',
            name='requested_product',
        ),
        migrations.AddField(
            model_name='requestedproductprocessingcancelreport',
            name='requested_product_processing',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='requested_product_processing_requested_product_processing_cancel_report', to='automation.requestedproductprocessing', verbose_name='محصول درخواستی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestedproductprocessingcancelreport',
            name='seller',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_requested_product_processing_cancel_report', to='accounts.sellerprofile', verbose_name='تلاش برای فروش توسط'),
        ),
    ]
