# Generated by Django 5.0.3 on 2024-05-31 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_deliveryprofile_delivery_allowance_and_more'),
        ('automation', '0008_remove_requestedproductprocessingcancelreport_requested_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='broker',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='brokers',
            field=models.ManyToManyField(blank=True, related_name='brokers_credit_card', to='accounts.profile', verbose_name='کارگزاران'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_credit_card', to='accounts.profile', verbose_name='مالک'),
        ),
    ]
