# Generated by Django 5.0.3 on 2024-04-14 10:54

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000, verbose_name='متن پیام')),
                ('file', models.FileField(blank=True, help_text='فابل های با فرمت jpg, png, zip قابل بررسی می باشد', null=True, upload_to='ticket-attached-files/', verbose_name='فایل')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='سازنده پیام')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='دریافت کننده پیام')),
            ],
            options={
                'verbose_name': 'تیکت - پیام',
                'verbose_name_plural': 'تیکت - پیام ها',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketChatBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('receiver', models.CharField(choices=[('پشتیبانی فنی', 'پشتیبانی فنی'), ('امور مالی', 'امور مالی'), ('ارسال مدرک', 'ارسال مدرک')], max_length=255, verbose_name='دریافت کننده')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('ticket_stage', models.CharField(choices=[('ایجاد شده', 'ایجاد شده'), ('پاسخ کاربر', 'پاسخ کاربر'), ('در حال بررسی', 'در حال بررسی'), ('پاسخ داده شده', 'پاسخ داده شده'), ('بسته شده', 'بسته شده')], default='ایجاد شده', max_length=50, verbose_name='وضعیت تیکت')),
                ('message_box', models.ManyToManyField(blank=True, to='tickets.messagecontent', verbose_name='پیام های تبادل شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='سازنده تیکت')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
            },
        ),
    ]
