# Generated by Django 5.0.3 on 2024-04-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticketchatbox_message_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('created', 'ایجاد شده'), ('pending', 'در حال بررسی'), ('admin_response', 'پاسخ ادمین'), ('closed', 'بسته شده'), ('user_response', 'پاسخ کاربر')], default='created', max_length=255, verbose_name='وضعیت تیکت'),
        ),
    ]
