# Generated by Django 5.0.3 on 2024-05-02 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='belong_to',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='has_seen_by_user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='title',
        ),
        migrations.AddField(
            model_name='ticket',
            name='has_seen_by_owner',
            field=models.BooleanField(default=False, verbose_name='دیده شده توسط کاربر'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='has_seen_by_receiver',
            field=models.BooleanField(default=False, verbose_name='دیده شده توسط کاربر'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_owner', to=settings.AUTH_USER_MODEL, verbose_name='متعلق به'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_receiver', to=settings.AUTH_USER_MODEL, verbose_name='ارسال شده به'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='subject',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='موضوع تیکت'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('created', 'ایجاد شده'), ('pending', 'در حال بررسی'), ('admin_response', 'پاسخ ادمین'), ('closed', 'بسته شده'), ('owner_response', 'پاسخ داده شده توسط فرستنده'), ('receiver_response', 'پاسخ داده شده توسط گیرنده')], default='created', max_length=255, verbose_name='وضعیت تیکت'),
        ),
    ]
