# Generated by Django 5.0.3 on 2024-05-02 16:19

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('tickets', '0004_remove_ticket_belong_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='has_seen_by_owner',
            field=models.BooleanField(default=False, verbose_name='دیده شده توسط فرستنده'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='has_seen_by_receiver',
            field=models.BooleanField(default=False, verbose_name='دیده شده توسط گیرنده'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=1024, null=True, verbose_name='موضوع اطلاعیه')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('attachments', models.ManyToManyField(blank=True, to='gallery.filegallery', verbose_name='ضمائم')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_notification', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
            ],
            options={
                'verbose_name': 'اطلاعیه',
                'verbose_name_plural': 'اطلاعیه ها',
            },
        ),
    ]
