# Generated by Django 5.0.3 on 2024-05-03 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_has_seen_by_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='subject',
        ),
    ]
